cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/science'

brew 'ack'
brew 'coreutils'
brew 'dislocker'
brew 'gcc'
brew 'git'
brew 'git-extras'
brew 'git-flow'
brew 'go'
brew 'imagemagick'
brew 'jp2a'
brew 'jq'
brew 'kubectl'
brew 'macvim'
brew 'matplotlib'
brew 'mysql'
brew 'numpy'
brew 'neo4j'
brew 'node'
brew 'openssl'
brew 'postgresql'
brew 'python3'
brew 'readline'
brew 'scipy'
brew 'unrar'
brew 'wget'
brew 'yarn'
brew 'youtube-dl'
brew 'zsh-syntax-highlighting'

cask '1password'
cask 'atom'
cask 'firefox'
cask 'google-chrome'
cask 'iterm2'
cask 'osxfuse'
cask 'seashore'
cask 'slack'
cask 'steam'
cask 'transmission'
cask 'tunnelbear'
cask 'vlc'
